"""The QA sheet - whether a drawing traced off this cloud can be trusted.

Written to disk in full; the tool returns six lines. That asymmetry is the
whole module in miniature: the owner gets the page, the model gets the verdict.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

VERDICTS = (
    (2.0, "TRUSTWORTHY", "trace dimensions from this directly"),
    (10.0, "USABLE", "trace shape; take critical dimensions from the tape"),
    (30.0, "SHAPE ONLY", "do not scale off this drawing"),
)


def verdict(worst_mm: float | None, levelled: bool, controlled: bool) -> tuple[str, str]:
    if not levelled:
        return "NOT READY", "run pc_level before trusting any measurement"
    if not controlled or worst_mm is None:
        return "UNVERIFIED", "no tape baseline - scale is the scanner's word alone"
    for limit, label, advice in VERDICTS:
        if worst_mm <= limit:
            return label, advice
    return "UNRELIABLE", "drift exceeds 30 mm - re-register from smaller scans"


def write_sheet(meta: dict[str, Any], out: Path) -> dict[str, Any]:
    chain = meta.get("chain") or []
    controls = meta.get("controls") or []
    level_step = next((s for s in reversed(chain) if s.get("op") == "level"), None)
    worst = max(
        (abs(float(c["measured_mm"]) - float(c["true_mm"])) for c in controls), default=None
    )
    label, advice = verdict(worst, level_step is not None, bool(controls))

    lines = [
        f"# Point-cloud QA — {meta['cloud_id']}",
        "",
        f"**Verdict: {label}** — {advice}",
        "",
        "## Cloud",
        "",
        f"- Points: {meta.get('count', 0):,}",
        f"- Colour: {'yes' if meta.get('has_colour') else 'no'} · "
        f"Intensity: {'yes' if meta.get('has_intensity') else 'no'}",
        f"- Source: {meta.get('source') or 'unknown'}",
        f"- Parent: {meta.get('parent') or '(root)'}",
        "",
        "## Transform chain",
        "",
        "| # | op | detail |",
        "|---|---|---|",
    ]
    for i, step in enumerate(chain, 1):
        detail = ", ".join(
            f"{k}={v}" for k, v in step.items() if k not in ("op", "at") and not isinstance(v, list)
        )
        lines.append(f"| {i} | `{step.get('op')}` | {detail or '—'} |")

    lines += ["", "## Level", ""]
    if level_step:
        lines += [
            f"- Residual tilt: **{level_step.get('residual_tilt_deg')}°**",
            f"- Floor-plane RMS: **{level_step.get('floor_rms_mm')} mm**",
            f"- Wall azimuth removed: **{level_step.get('wall_azimuth_deg')}°**",
        ]
    else:
        lines.append("- Not levelled. Every dimension below is in the scanner's arbitrary frame.")

    lines += ["", "## Control baselines", ""]
    if controls:
        lines += ["| name | measured mm | tape mm | delta mm | ppm |", "|---|---|---|---|---|"]
        for c in controls:
            delta = float(c["measured_mm"]) - float(c["true_mm"])
            lines.append(
                f"| {c['name']} | {c['measured_mm']:.1f} | {c['true_mm']:.1f} | "
                f"{delta:+.1f} | {delta / float(c['true_mm']) * 1e6:+.0f} |"
            )
        lines += ["", f"Worst baseline error: **{worst:.1f} mm**"]
    else:
        lines.append(
            "None recorded. Phone LiDAR drifts 6-9 cm over a building; without a tape "
            "baseline this cloud's scale is unverified. See `pc_control_add`."
        )

    lines += [
        "",
        "## Registration",
        "",
        "This lane does not register clouds. Use `capture_register` (CloudCompare ICP onto "
        "the design datum, with a refusing RMS gate), then re-open the aligned result.",
        "",
        "---",
        "",
        "*Generated by TEE `pc_report` (A67). Numbers are measurements, not approvals.*",
        "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))

    digest = {
        "path": str(out),
        "verdict": label,
        "advice": advice,
        "points": int(meta.get("count", 0)),
        "steps": len(chain),
        "baselines": len(controls),
    }
    if level_step:
        digest["residual_tilt_deg"] = level_step.get("residual_tilt_deg")
        digest["floor_rms_mm"] = level_step.get("floor_rms_mm")
    if worst is not None:
        digest["worst_control_mm"] = round(worst, 1)
    return digest
