"""Version-matched Blender API docs search (principle P5, Phase 4).

Hallucinated bpy calls are the #1 catalogued friction point. Instead of
shipping doc files that can drift, the index is generated by introspecting
the LIVE Blender over the bridge (`bl_rna` reflection) - version-matched by
construction - then cached on disk per version and searched server-side.
Search results are compact (path + one-line doc + a few params); full detail
for one symbol is a separate call, straight from the live runtime.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

from tee.kernel.errors import TeeError

if TYPE_CHECKING:
    from tee.adapters.blender.adapter import BlenderAdapter

_INDEX_TIMEOUT = 120.0
_MAX_RESULTS = 25

INDEX_PROGRAM = """
import bpy

entries = []

for cat_name in dir(bpy.ops):
    if cat_name.startswith("_"):
        continue
    cat = getattr(bpy.ops, cat_name)
    for op_name in dir(cat):
        if op_name.startswith("_"):
            continue
        try:
            rna = getattr(cat, op_name).get_rna_type()
        except Exception:
            continue
        params = []
        for p in rna.properties:
            if p.identifier != "rna_type":
                params.append(p.identifier + ":" + p.type.lower())
        entries.append({
            "path": "bpy.ops.%s.%s" % (cat_name, op_name),
            "kind": "operator",
            "doc": (rna.description or "").strip(),
            "params": params[:40],
        })

for type_name in dir(bpy.types):
    t = getattr(bpy.types, type_name, None)
    rna = getattr(t, "bl_rna", None)
    if rna is None:
        continue
    props = []
    for p in rna.properties:
        if p.identifier != "rna_type":
            props.append(p.identifier + ":" + p.type.lower())
    entries.append({
        "path": "bpy.types." + type_name,
        "kind": "type",
        "doc": (rna.description or "").strip(),
        "params": props[:80],
    })

result = {"version": list(bpy.app.version), "entries": entries}
"""


def program_api_detail(path: str) -> str:
    """Full live detail for one symbol: properties with types, descriptions
    and enum items, straight from the running Blender's RNA."""
    return f"""
import bpy

path = {path!r}
parts = path.split(".")
rna = None
if path.startswith("bpy.ops.") and len(parts) == 4:
    try:
        rna = getattr(getattr(bpy.ops, parts[2]), parts[3]).get_rna_type()
    except Exception:
        rna = None
elif path.startswith("bpy.types.") and len(parts) == 3:
    t = getattr(bpy.types, parts[2], None)
    rna = getattr(t, "bl_rna", None)

if rna is None:
    result = {{"found": False}}
else:
    props = []
    for p in rna.properties:
        if p.identifier == "rna_type":
            continue
        entry = {{
            "name": p.identifier,
            "type": p.type.lower(),
            "doc": (p.description or "").strip(),
        }}
        if p.type == 'ENUM':
            try:
                entry["items"] = [i.identifier for i in p.enum_items][:25]
            except Exception:
                pass
        if getattr(p, "is_readonly", False):
            entry["readonly"] = True
        props.append(entry)
    result = {{
        "found": True,
        "path": path,
        "doc": (rna.description or "").strip(),
        "properties": props[:120],
    }}
"""


class BlenderDocs:
    def __init__(self, adapter: BlenderAdapter, cache_dir: Path | str | None = None):
        self.adapter = adapter
        self.cache_dir = Path(cache_dir) if cache_dir else Path.home() / ".cache" / "tee"
        self._entries: list[dict[str, Any]] | None = None
        self._version: str | None = None

    # -- index lifecycle ---------------------------------------------------

    def ensure_index(self) -> int:
        """Load the per-version index, building it from the live Blender on
        first use. Returns the number of indexed symbols."""
        if self._entries is not None:
            return len(self._entries)
        info = self.adapter.info()
        if not info.connected:
            raise TeeError(
                "blender_unreachable",
                "Cannot build the API index: no Blender bridge.",
                fix="Check tee_status.",
            )
        version = info.version.split()[0]
        cache_file = self.cache_dir / f"bpy-api-{version}.json"
        if cache_file.exists():
            try:
                data = json.loads(cache_file.read_text())
                self._entries = data["entries"]
                self._version = version
                return len(self._entries)
            except (json.JSONDecodeError, KeyError, OSError):
                cache_file.unlink(missing_ok=True)
        data = self.adapter._call(INDEX_PROGRAM, timeout=_INDEX_TIMEOUT)
        self._entries = data["entries"]
        self._version = version
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        tmp = cache_file.with_suffix(".tmp")
        tmp.write_text(json.dumps({"entries": self._entries}))
        tmp.replace(cache_file)
        return len(self._entries)

    # -- queries -----------------------------------------------------------

    def search(self, query: str, limit: int = 10) -> dict[str, Any]:
        count = self.ensure_index()
        limit = max(1, min(limit, _MAX_RESULTS))
        words = [w for w in re.split(r"[^a-z0-9_]+", query.lower()) if w]
        scored: list[tuple[float, dict[str, Any]]] = []
        for entry in self._entries or []:
            path = entry["path"].lower()
            doc = entry["doc"].lower()
            score = 0.0
            for word in words:
                if word in path:
                    # exact segment match beats substring
                    score += 4.0 if word in path.replace(".", " ").split() else 2.0
                elif word in doc:
                    score += 1.0
            if score > 0:
                scored.append((score, entry))
        scored.sort(key=lambda pair: (-pair[0], pair[1]["path"]))
        results = []
        for _, entry in scored[:limit]:
            item: dict[str, Any] = {"path": entry["path"], "kind": entry["kind"]}
            if entry["doc"]:
                item["doc"] = entry["doc"].splitlines()[0][:140]
            if entry["params"]:
                item["params"] = entry["params"][:12]
                if len(entry["params"]) > 12:
                    item["more_params"] = len(entry["params"]) - 12
            results.append(item)
        payload: dict[str, Any] = {
            "blender": self._version,
            "indexed_symbols": count,
            "results": results,
        }
        if not results:
            payload["hint"] = "no matches; try other words, e.g. the object/property name"
        return payload

    def detail(self, path: str) -> dict[str, Any]:
        data = self.adapter._call(program_api_detail(path), timeout=30.0)
        if not data.get("found"):
            suggestions = self.search(path.rsplit(".", 1)[-1], limit=3)["results"]
            hint = ", ".join(s["path"] for s in suggestions) or "bl_search_docs"
            raise TeeError(
                "unknown_api_symbol",
                f"No symbol '{path}' in this Blender.",
                fix=f"Closest matches: {hint}.",
            )
        return data
