"""KB index: manifest loading, cache, drift check, section addressing (16.1).

The corpus's own `manifest.json` (generated by its `00_meta/rebuild.py`) is
the single index source - per-file id, title, domain, tags, jurisdiction,
status, confidence, words, sha256 and summary. TEE never writes into the
corpus; the only thing written is the cache under `<project>/.tee/kb/`.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import re
from pathlib import Path
from typing import Any

from tee.kernel.errors import TeeError

MANIFEST_REQUIRED = ("generated", "totals", "domains", "files")
RECORD_KEYS = (
    "path",
    "id",
    "title",
    "domain",
    "tags",
    "jurisdiction",
    "status",
    "confidence",
    "words",
    "sha256",
    "summary",
)
DRIFT_LIST_CAP = 20
_HEADING = re.compile(r"^(#{1,2})\s+(.*)$", re.M)


def resolve_root(project_root: Path | str, configured: str | None) -> Path | None:
    """Find the corpus root: explicit config first, then the project's own
    `knowledge-base/` mirror, then the TEE source checkout's mirror. None
    means the module stays inactive - never a guess at some other folder."""
    project = Path(project_root)
    if configured:
        root = Path(configured).expanduser()
        if not root.is_absolute():
            root = project / root
        return root  # explicit config is returned even if broken: fail loud there
    candidates = [
        project / "knowledge-base",
        Path(__file__).resolve().parents[4] / "knowledge-base",  # source checkout
    ]
    for candidate in candidates:
        if (candidate / "manifest.json").is_file():
            return candidate
    return None


def load_manifest(root: Path) -> dict[str, Any]:
    path = root / "manifest.json"
    if not path.is_file():
        raise TeeError(
            "kb_no_manifest",
            f"no manifest.json under '{root}'.",
            fix="Point [kb] root in .tee/config.toml at the Expert Knowledge "
            "Base corpus (the folder holding manifest.json), or run its "
            "00_meta/rebuild.py to generate one.",
        )
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise TeeError(
            "kb_bad_manifest",
            f"manifest.json under '{root}' is unreadable: {exc}.",
            fix="Regenerate it with the corpus's own 00_meta/rebuild.py.",
        ) from exc
    missing = [key for key in MANIFEST_REQUIRED if key not in manifest]
    if missing or not isinstance(manifest.get("files"), list):
        raise TeeError(
            "kb_bad_manifest",
            f"manifest.json is missing {missing or ['a files list']}.",
            fix="Regenerate it with the corpus's own 00_meta/rebuild.py.",
        )
    return manifest


class KbIndex:
    """Manifest-derived index with a cache keyed on the manifest's
    `generated` date. Drift is computed at build and re-checkable on demand;
    a stale index still serves queries, visibly flagged."""

    def __init__(self, root: Path, project_root: Path | str):
        self.root = root
        self.cache_path = Path(project_root) / ".tee" / "kb" / "index.json"
        self._data: dict[str, Any] | None = None

    # -- build / cache -----------------------------------------------------

    def load(self, rebuild: bool = False) -> dict[str, Any]:
        if self._data is not None and not rebuild:
            return self._data
        generated = None
        if not rebuild and self.cache_path.is_file():
            try:
                cached = json.loads(self.cache_path.read_text(encoding="utf-8"))
                generated = cached.get("generated")
                if cached.get("root") == str(self.root) and generated is not None:
                    manifest_generated = load_manifest(self.root).get("generated")
                    if generated == manifest_generated:
                        self._data = cached
                        return cached
            except (json.JSONDecodeError, OSError):
                pass  # unreadable cache is just rebuilt
        self._data = self._build()
        return self._data

    def _build(self) -> dict[str, Any]:
        manifest = load_manifest(self.root)
        records = []
        for entry in manifest["files"]:
            record = {key: entry.get(key, "") for key in RECORD_KEYS}
            record["headings"] = self._headings_of(entry.get("path", ""))
            records.append(record)
        data = {
            "root": str(self.root),
            "generated": manifest.get("generated"),
            "name": manifest.get("name", ""),
            "totals": manifest.get("totals", {}),
            "domains": manifest.get("domains", []),
            "records": records,
            "drift": self._drift(manifest),
        }
        try:
            self.cache_path.parent.mkdir(parents=True, exist_ok=True)
            self.cache_path.write_text(json.dumps(data), encoding="utf-8")
        except OSError:
            pass  # cache is an optimization, never a requirement
        return data

    def _headings_of(self, rel_path: str) -> list[str]:
        try:
            body = self._body(rel_path)
        except TeeError:
            return []
        return [m.group(2).strip() for m in _HEADING.finditer(body) if len(m.group(1)) == 2]

    def _drift(self, manifest: dict[str, Any]) -> dict[str, Any]:
        missing, changed = [], []
        for entry in manifest["files"]:
            path = self.root / entry.get("path", "")
            if not path.is_file():
                missing.append(entry.get("path"))
                continue
            digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
            if digest != entry.get("sha256"):
                changed.append(entry.get("path"))
        stale = bool(missing or changed)
        drift: dict[str, Any] = {
            "stale": stale,
            "checked_files": len(manifest["files"]),
            "missing": missing[:DRIFT_LIST_CAP],
            "changed": changed[:DRIFT_LIST_CAP],
            "missing_count": len(missing),
            "changed_count": len(changed),
        }
        if stale:
            drift["fix"] = (
                "the corpus no longer matches its manifest - run its "
                "00_meta/rebuild.py (results still serve, flagged stale)"
            )
        return drift

    def recheck_drift(self) -> dict[str, Any]:
        """Re-hash the corpus against the manifest and update the cache."""
        data = self.load()
        data["drift"] = self._drift(load_manifest(self.root))
        with contextlib.suppress(OSError):
            self.cache_path.write_text(json.dumps(data), encoding="utf-8")
        return data["drift"]

    # -- lookups -----------------------------------------------------------

    def records(self) -> list[dict[str, Any]]:
        return self.load()["records"]

    def record(self, file_id: str) -> dict[str, Any]:
        wanted = str(file_id).strip()
        for record in self.records():
            if record["id"] == wanted or record["path"] == wanted:
                return record
        near = [r["id"] for r in self.records() if wanted.lower() in r["id"].lower()][:5]
        hint = f" Near matches: {', '.join(near)}." if near else ""
        raise TeeError(
            "kb_unknown_id",
            f"no corpus file with id '{file_id}'.{hint}",
            fix="Use an id from kb_search results.",
        )

    # -- section addressing ------------------------------------------------

    def _body(self, rel_path: str) -> str:
        path = self.root / rel_path
        try:
            raw = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            raise TeeError(
                "kb_unreadable",
                f"cannot read '{rel_path}': {exc}.",
                fix="Check the [kb] root and re-run kb_status.",
            ) from exc
        if raw.startswith("---"):
            end = raw.find("\n---", 3)
            if end != -1:
                raw = raw[end + 4 :]
        return raw

    def sections(self, record: dict[str, Any]) -> list[dict[str, Any]]:
        """H2 sections with word sizes; text before the first H2 is 'intro'."""
        body = self._body(record["path"])
        marks = [m for m in _HEADING.finditer(body) if len(m.group(1)) == 2]
        out: list[dict[str, Any]] = []
        intro_end = marks[0].start() if marks else len(body)
        intro = body[:intro_end]
        if intro.strip():
            out.append({"section": "intro", "words": len(intro.split())})
        for i, mark in enumerate(marks):
            end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
            out.append(
                {
                    "section": mark.group(2).strip(),
                    "words": len(body[mark.end() : end].split()),
                }
            )
        return out

    def section_text(self, record: dict[str, Any], section: str) -> str:
        body = self._body(record["path"])
        marks = [m for m in _HEADING.finditer(body) if len(m.group(1)) == 2]
        wanted = section.strip().lower()
        if wanted == "intro":
            end = marks[0].start() if marks else len(body)
            return body[:end].strip()
        titles = [m.group(2).strip() for m in marks]
        exact = [i for i, t in enumerate(titles) if t.lower() == wanted]
        partial = [i for i, t in enumerate(titles) if wanted in t.lower()]
        hits = exact or partial
        if not hits:
            raise TeeError(
                "kb_no_section",
                f"'{record['id']}' has no section matching '{section}'.",
                fix="Sections: " + "; ".join(["intro", *titles]),
            )
        if len(hits) > 1:
            raise TeeError(
                "kb_ambiguous_section",
                f"'{section}' matches {len(hits)} sections in '{record['id']}'.",
                fix="Pick one: " + "; ".join(titles[i] for i in hits),
            )
        i = hits[0]
        end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
        return body[marks[i].start() : end].strip()
